### ISSUE TITLE
nw-gyp rebuild --target=0.39.2 fails with compilation error

### ISSUE THREAD

**Issue by sridharpg** [tojocky/node-printer#257]
I get the following compilation errors when nwjs target is set above 0.36.*(in my case I tried with 0.39.2)

```
../src/node_printer_posix.cc:121:70: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
        result_printer_job->Set(V8_STRING_NEW_UTF8("completedTime"), V8_VALUE_NEW(Date, completedTime));
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../src/node_printer_posix.cc:122:69: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
        result_printer_job->Set(V8_STRING_NEW_UTF8("creationTime"), V8_VALUE_NEW(Date, creationTime));
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../src/node_printer_posix.cc:123:71: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
        result_printer_job->Set(V8_STRING_NEW_UTF8("processingTime"), V8_VALUE_NEW(Date, processingTime));
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../src/node_printer_posix.cc:262:54: error: no matching member function for call to 'GetPropertyNames'
            v8::Local<v8::Array> props = iV8Options->GetPropertyNames();
                                         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

**Comment by sridharpg** [comment]
Just to be clear, 

`nw-gyp rebuild --target=0.36.4` compiles without issues. If the target is over 0.37, it nw-gyp starts failing.

**Comment by sridharpg** [comment]
Created a [pull request](https://github.com/tojocky/node-printer/pull/258/files) for this one.

**Comment by rurigk** [comment]
@sridharpg Your fix work with electron 5.0.1 :D
